### ISSUE TITLE
Installation Clarifications

### ISSUE THREAD

**Issue by leti332** [Kainmueller-Lab/PatchPerPix#5]
Hi all,

The package would benefit from the following installation clarifications before running the examples.
1. Tensorflow 1 needs to be installed _before_ python
2. malis needs to be installed from GitHub due to new updates which are not reflected in pip install
3. colorcet needs to be installed

**Comment by abred** [comment]
Hi,
thank you for reporting your issues.
1.) Could you please clarify what you mean by this and why this would be necessary? Tensorflow is a python package and thus depends on python
2.) Thank you, this is more related to a commit I made to gunpowder for another project without thinking about its effects on PatchPerPix. I will fix it
3.) I thought I had already fixed that, but apparently not, will fix it.

**Comment by leti332** [comment]
Hi,
If you create the conda environment and later pip install Tensorflow, the default python 3 installed is not compatible with Tensorflow1. To avoid encountering this error, we installed Tensorflow1 when creating the environment so that it would automatically download the correct version of python. 

Here's an example of what we used.

`conda create -n <env_name> tensorflow-gpu=1 `

**Comment by abred** [comment]
ok, that's interesting. Maybe the difference is just that one time you use pip to install tensorflow and in the other case conda (which get their packages from different sources). I'll add a comment in the Readme. Thanks

**Comment by abred** [comment]
cad3eefb19783bf15adcb26af1b1ea1c85fc40fe
